USE REGISTRO_UNIVERSITARIO;

SELECT* FROM FACULTAD;
SELECT* FROM CARRERA;
SELECT* FROM MAESTRIA;
SELECT* FROM DEPARTAMENTO;
SELECT* FROM ESTUDIANTE;
SELECT* FROM MATRICULA;
SELECT* FROM CLASE;
SELECT* FROM DOCENTE;
SELECT* FROM laboratorio;

SELECT E.nombreEstudiante,E.numCuentaEstu, C.nombreCarrera FROM ESTUDIANTE E INNER JOIN CARRERA C ON E.carrera=C.idCarrera ;
